<?php

namespace Systha\systhatech\database\seeds;

use Illuminate\Database\Seeder;

class FrontendMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('frontend_menus')->delete();
        
        \DB::table('frontend_menus')->insert(array (
            0 => 
            array (
                'category_id' => NULL,
                'created_at' => '2021-12-13 14:32:28',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 1,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/',
                'location_footer' => '',
                'menu_code' => 'custom_development',
                'menu_location' => '',
                'menu_name' => 'Custom Development',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'module',
                'updated_at' => '2022-03-01 12:49:09',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            1 => 
            array (
                'category_id' => NULL,
                'created_at' => '2021-12-13 14:33:11',
                'deleted_at' => '2022-03-01 12:06:07',
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 2,
                'is_active' => 1,
                'is_deleted' => 1,
                'link' => '/',
                'location_footer' => '',
                'menu_code' => 'subscription_software',
                'menu_location' => 'header',
                'menu_name' => 'Products1',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => 0,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-03-01 12:06:07',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            2 => 
            array (
                'category_id' => NULL,
                'created_at' => '2021-12-13 14:33:32',
                'deleted_at' => '2022-02-03 19:16:34',
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 3,
                'is_active' => 1,
                'is_deleted' => 1,
                'link' => '/',
                'location_footer' => NULL,
                'menu_code' => 'pricing',
                'menu_location' => 'header',
                'menu_name' => 'Pricing',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-03 19:16:34',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            3 => 
            array (
                'category_id' => NULL,
                'created_at' => '2021-12-13 14:33:55',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'link' => '/',
                'location_footer' => '',
                'menu_code' => 'support',
                'menu_location' => 'header',
                'menu_name' => 'Support',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-03 19:18:44',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            4 => 
            array (
                'category_id' => NULL,
                'created_at' => '2021-12-13 14:34:29',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 5,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/',
                'location_footer' => 'footer',
                'menu_code' => 'web',
                'menu_location' => '',
                'menu_name' => 'Website Design',
                'parent_id' => 1,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-28 14:01:54',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            5 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 6,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/',
                'location_footer' => 'footer',
                'menu_code' => 'mobile_app',
                'menu_location' => '',
                'menu_name' => 'Mobile App',
                'parent_id' => 1,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-28 14:02:05',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            6 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 7,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/',
                'location_footer' => 'footer',
                'menu_code' => 'adv_web_dev',
                'menu_location' => '',
                'menu_name' => 'Advanced Web Development',
                'parent_id' => 1,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-28 14:02:17',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            7 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 8,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/',
                'location_footer' => 'footer',
                'menu_code' => 'business_process_auto',
                'menu_location' => '',
                'menu_name' => 'Business Process Automation',
                'parent_id' => 1,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-28 14:02:26',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            8 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 9,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/',
                'location_footer' => '',
                'menu_code' => 'hire_pro',
                'menu_location' => '',
                'menu_name' => 'Hire Us',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-03-01 09:09:56',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            9 => 
            array (
                'category_id' => NULL,
                'created_at' => '2021-12-13 18:35:21',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 10,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/ecommerce',
                'location_footer' => '',
                'menu_code' => 'ecommerce',
                'menu_location' => 'header',
                'menu_name' => 'Ecommerce',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => 1,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-17 14:23:41',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            10 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 11,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qfoodtruck',
                'location_footer' => '',
                'menu_code' => 'foodtruck',
                'menu_location' => 'header',
                'menu_name' => 'Food Truck',
                'parent_id' => 2,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-18 20:30:29',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            11 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 12,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qpestcontrol',
                'location_footer' => '',
                'menu_code' => 'pest_control',
                'menu_location' => 'header',
                'menu_name' => 'Pest Control1',
                'parent_id' => 2,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-03-01 09:53:45',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            12 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 13,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qnonprofit',
                'location_footer' => '',
                'menu_code' => 'non_profit',
                'menu_location' => 'header',
                'menu_name' => 'Non Profit',
                'parent_id' => 2,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-18 22:21:55',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            13 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 14,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qauction',
                'location_footer' => '',
                'menu_code' => 'auction',
                'menu_location' => 'header',
                'menu_name' => 'Auction Real Estate',
                'parent_id' => 2,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-18 22:24:38',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            14 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 15,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qpestcontrol',
                'location_footer' => '',
                'menu_code' => 'saloon',
                'menu_location' => 'header',
                'menu_name' => 'Saloon',
                'parent_id' => 2,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-18 22:24:55',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            15 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 16,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qtimeclock',
                'location_footer' => '',
                'menu_code' => 'clock',
                'menu_location' => 'header',
                'menu_name' => 'Time Clock',
                'parent_id' => 2,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-03-01 10:09:21',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            16 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 17,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qpestcontrol',
                'location_footer' => NULL,
                'menu_code' => 'support',
                'menu_location' => 'header',
                'menu_name' => 'Remote Employee Tracking',
                'parent_id' => 2,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => NULL,
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            17 => 
            array (
                'category_id' => NULL,
                'created_at' => NULL,
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 18,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qcraterental',
                'location_footer' => '',
                'menu_code' => 'crate',
                'menu_location' => 'header',
                'menu_name' => 'Rental',
                'parent_id' => 2,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-18 20:29:44',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            18 => 
            array (
                'category_id' => NULL,
                'created_at' => '2021-12-14 19:11:16',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 19,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/home',
                'location_footer' => '',
                'menu_code' => 'home',
                'menu_location' => '',
                'menu_name' => 'Home',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => 1,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-17 13:12:59',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => NULL,
                'vendor_template_id' => 1,
            ),
            19 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-01-29 08:49:48',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 20,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qecommerce',
                'location_footer' => '',
                'menu_code' => 'qecommerce',
                'menu_location' => '',
                'menu_name' => 'Quote Ecommerce',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-16 19:28:36',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            20 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-05 19:12:16',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 21,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qfoodtruck',
                'location_footer' => '',
                'menu_code' => 'qfoodtruck',
                'menu_location' => '',
                'menu_name' => 'Q FoodTruck',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-17 13:29:03',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            21 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-06 19:21:18',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 22,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qpestcontrol',
                'location_footer' => '',
                'menu_code' => 'qpestcontrol',
                'menu_location' => '',
                'menu_name' => 'Q Pest Control',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-16 19:34:43',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            22 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-06 19:38:28',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 23,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qcraterental',
                'location_footer' => '',
                'menu_code' => 'qcraterental',
                'menu_location' => '',
                'menu_name' => 'Q Crate Rental',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-16 19:35:34',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            23 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-06 19:47:16',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 24,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qauction',
                'location_footer' => '',
                'menu_code' => 'qauction',
                'menu_location' => '',
                'menu_name' => 'Q Auction',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-16 19:35:19',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            24 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-16 12:26:11',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 25,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qnonprofit',
                'location_footer' => '',
                'menu_code' => 'qsaloon',
                'menu_location' => '',
                'menu_name' => 'Q Saloon',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-16 19:35:12',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            25 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-16 12:32:00',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 26,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qpestcontrol',
                'location_footer' => '',
                'menu_code' => 'qnonprofit',
                'menu_location' => '',
                'menu_name' => 'Q Non Profit',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-17 05:12:42',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            26 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-16 12:34:59',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 27,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/qtimeclock',
                'location_footer' => '',
                'menu_code' => 'qtimeclock',
                'menu_location' => '',
                'menu_name' => 'Q Time Clock',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-17 13:27:15',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            27 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-16 14:02:55',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 28,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/aboutus',
                'location_footer' => '',
                'menu_code' => 'aboutus',
                'menu_location' => 'header',
                'menu_name' => 'About Us',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => 5,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-17 14:11:44',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            28 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-18 07:49:15',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 29,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/quote/',
                'location_footer' => '',
                'menu_code' => 'quote',
                'menu_location' => '',
                'menu_name' => 'quote',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-18 22:22:16',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            29 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-18 09:04:01',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 30,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/portfolio',
                'location_footer' => '',
                'menu_code' => 'portfolio',
                'menu_location' => 'header',
                'menu_name' => 'Portfolio',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => 3,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-18 22:24:12',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            30 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-18 22:34:52',
                'deleted_at' => NULL,
                'detailpage_link' => '32',
                'icon' => NULL,
                'id' => 31,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/blog/',
                'location_footer' => '',
                'menu_code' => 'blog',
                'menu_location' => 'header',
                'menu_name' => 'Blog',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => 4,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-19 19:47:26',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            31 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-02-18 22:46:27',
                'deleted_at' => NULL,
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 32,
                'is_active' => 1,
                'is_deleted' => 0,
                'link' => '/cms/',
                'location_footer' => '',
                'menu_code' => 'blogdetails',
                'menu_location' => '',
                'menu_name' => 'Blog Details',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-02-21 13:23:20',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
            32 => 
            array (
                'category_id' => NULL,
                'created_at' => '2022-03-01 13:22:37',
                'deleted_at' => '2022-03-01 13:22:50',
                'detailpage_link' => NULL,
                'icon' => NULL,
                'id' => 33,
                'is_active' => 1,
                'is_deleted' => 1,
                'link' => '/',
                'location_footer' => NULL,
                'menu_code' => 'test',
                'menu_location' => 'header',
                'menu_name' => 'test',
                'parent_id' => NULL,
                'section' => NULL,
                'seq_no' => NULL,
                'target' => NULL,
                'type' => 'component',
                'updated_at' => '2022-03-01 13:22:50',
                'userc_id' => NULL,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'vendor_id' => 1,
                'vendor_template_id' => 1,
            ),
        ));
        
        
    }
}