<?php

namespace Systha\systhatech\database\seeds;

use Illuminate\Database\Seeder;

class VendorMenuComponentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
 \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        \DB::table('vendor_menu_components')->delete();
        
        \DB::table('vendor_menu_components')->insert(array (
            0 => 
            array (
                'bg_color' => '#bc3838',
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-26 20:04:25',
                'description' => NULL,
                'id' => 1,
                'page_id' => 19,
                'ref_comp_id' => NULL,
                'ref_post' => 'header',
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => '#f45757',
                'type' => 'file',
                'updated_at' => '2022-01-11 12:24:09',
                'vendor_template_id' => 1,
            ),
            1 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-26 20:04:40',
                'description' => NULL,
                'id' => 2,
                'page_id' => 19,
                'ref_comp_id' => '2',
                'ref_post' => '19',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#7f9707',
                'type' => 'file',
                'updated_at' => '2022-02-03 14:51:29',
                'vendor_template_id' => 1,
            ),
            2 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'banner_digital',
                'created_at' => '2021-12-26 20:04:54',
                'description' => NULL,
                'id' => 3,
                'page_id' => 19,
                'ref_comp_id' => '3',
                'ref_post' => '19',
                'seq_no' => 2,
                'title' => 'Banner Digital',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 14:51:49',
                'vendor_template_id' => 1,
            ),
            3 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-26 20:05:12',
                'description' => NULL,
                'id' => 4,
                'page_id' => 19,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 6,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-08 09:04:24',
                'vendor_template_id' => 1,
            ),
            4 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-26 20:05:29',
                'description' => '<p>test</p>',
                'id' => 5,
                'page_id' => 19,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 7,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-08 09:04:24',
                'vendor_template_id' => 1,
            ),
            5 => 
            array (
                'bg_color' => '#fbffe0',
                'component_id' => NULL,
                'component_name' => 'services_digital',
                'created_at' => '2021-12-27 14:28:50',
                'description' => '<div>Effortlessly run and manage your business with our low cost full features products. <br></div>',
                'id' => 7,
                'page_id' => 19,
                'ref_comp_id' => '7',
                'ref_post' => '19',
                'seq_no' => 3,
                'title' => 'Our Products',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 14:52:50',
                'vendor_template_id' => 1,
            ),
            6 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'services',
                'created_at' => '2021-12-27 18:58:45',
                'description' => NULL,
                'id' => 8,
                'page_id' => 19,
                'ref_comp_id' => '8',
                'ref_post' => '19',
                'seq_no' => 4,
                'title' => 'Development Services',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 14:53:50',
                'vendor_template_id' => 1,
            ),
            7 => 
            array (
                'bg_color' => '#fbffe0',
                'component_id' => NULL,
                'component_name' => 'work',
                'created_at' => '2021-12-27 19:11:09',
                'description' => NULL,
                'id' => 9,
                'page_id' => 19,
                'ref_comp_id' => '9',
                'ref_post' => '19',
                'seq_no' => 5,
                'title' => 'Our Recent Work',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 14:54:41',
                'vendor_template_id' => 1,
            ),
            8 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-29 08:51:12',
                'description' => NULL,
                'id' => 11,
                'page_id' => 10,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-29 08:51:12',
                'vendor_template_id' => 1,
            ),
            9 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-29 08:51:26',
                'description' => NULL,
                'id' => 12,
                'page_id' => 10,
                'ref_comp_id' => '12',
                'ref_post' => '10',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 15:02:51',
                'vendor_template_id' => 1,
            ),
            10 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-29 08:51:38',
                'description' => NULL,
                'id' => 13,
                'page_id' => 10,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 8,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-17 14:28:15',
                'vendor_template_id' => 1,
            ),
            11 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-29 08:51:53',
                'description' => NULL,
                'id' => 14,
                'page_id' => 10,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 9,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-17 14:28:15',
                'vendor_template_id' => 1,
            ),
            12 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'banner_free',
                'created_at' => '2021-12-29 08:55:04',
                'description' => NULL,
                'id' => 15,
                'page_id' => 10,
                'ref_comp_id' => NULL,
                'ref_post' => '10',
                'seq_no' => 2,
                'title' => 'Banner Free',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-24 07:36:36',
                'vendor_template_id' => 1,
            ),
            13 => 
            array (
                'bg_color' => '#fbffe0',
                'component_id' => NULL,
                'component_name' => 'features',
                'created_at' => '2021-12-29 14:18:52',
                'description' => NULL,
                'id' => 16,
                'page_id' => 10,
                'ref_comp_id' => '16',
                'ref_post' => '10',
                'seq_no' => 3,
                'title' => 'Features',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 18:53:28',
                'vendor_template_id' => 1,
            ),
            14 => 
            array (
                'bg_color' => '#fbffe0',
                'component_id' => NULL,
                'component_name' => 'process',
                'created_at' => '2021-12-29 14:25:26',
                'description' => NULL,
                'id' => 17,
                'page_id' => 10,
                'ref_comp_id' => '17',
                'ref_post' => '10',
                'seq_no' => 5,
                'title' => 'How do we work ?',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 19:00:24',
                'vendor_template_id' => 1,
            ),
            15 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'app_screen',
                'created_at' => '2021-12-29 14:25:43',
                'description' => NULL,
                'id' => 18,
                'page_id' => 10,
                'ref_comp_id' => '18',
                'ref_post' => '10',
                'seq_no' => 6,
                'title' => 'App Screen',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 19:03:48',
                'vendor_template_id' => 1,
            ),
            16 => 
            array (
                'bg_color' => '#fbffe0',
                'component_id' => NULL,
                'component_name' => 'contact_graphic',
                'created_at' => '2021-12-29 14:36:17',
                'description' => '<p>Ecommerce</p>',
                'id' => 22,
                'page_id' => 10,
                'ref_comp_id' => NULL,
                'ref_post' => '10',
                'seq_no' => 7,
                'title' => 'Contact Graphic',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-23 19:31:38',
                'vendor_template_id' => 1,
            ),
            17 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'work_free',
                'created_at' => '2021-12-29 14:38:14',
                'description' => NULL,
                'id' => 23,
                'page_id' => 10,
                'ref_comp_id' => '23',
                'ref_post' => '10',
                'seq_no' => 4,
                'title' => 'Our Recent Work',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 19:03:13',
                'vendor_template_id' => 1,
            ),
            18 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-31 17:14:16',
                'description' => NULL,
                'id' => 25,
                'page_id' => 5,
                'ref_comp_id' => NULL,
                'ref_post' => '10',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-06 14:34:11',
                'vendor_template_id' => 1,
            ),
            19 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-31 17:14:42',
                'description' => NULL,
                'id' => 26,
                'page_id' => 5,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 9,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-31 17:14:42',
                'vendor_template_id' => 1,
            ),
            20 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-31 17:15:14',
                'description' => NULL,
                'id' => 28,
                'page_id' => 5,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 10,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-31 17:15:14',
                'vendor_template_id' => 1,
            ),
            21 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'banner_digital',
                'created_at' => '2021-12-31 17:18:00',
                'description' => NULL,
                'id' => 29,
                'page_id' => 5,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 2,
                'title' => 'Banner Digital',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-31 17:18:00',
                'vendor_template_id' => 1,
            ),
            22 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'services_item',
                'created_at' => '2022-01-03 14:29:03',
                'description' => 'We make the collaboration of people and interface more intensive and exciting.',
                'id' => 31,
                'page_id' => 5,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Marketing Service',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-04 13:16:13',
                'vendor_template_id' => 1,
            ),
            23 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'tech_we_use',
                'created_at' => '2022-01-03 14:32:58',
                'description' => '<p>test</p>',
                'id' => 32,
                'page_id' => 5,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Tech We Use',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-04 18:53:24',
                'vendor_template_id' => 1,
            ),
            24 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'contact_graphic',
                'created_at' => '2022-01-03 14:34:05',
                'description' => NULL,
                'id' => 33,
                'page_id' => 5,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 5,
                'title' => 'Contact Graphic',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-03 14:34:05',
                'vendor_template_id' => 1,
            ),
            25 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2022-01-04 18:54:19',
                'description' => NULL,
                'id' => 34,
                'page_id' => 3,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-04 18:54:19',
                'vendor_template_id' => 1,
            ),
            26 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2022-01-04 18:55:08',
                'description' => NULL,
                'id' => 35,
                'page_id' => 3,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Nav',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-04 18:55:08',
                'vendor_template_id' => 1,
            ),
            27 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2022-01-04 18:55:22',
                'description' => NULL,
                'id' => 36,
                'page_id' => 3,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 8,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-04 18:55:22',
                'vendor_template_id' => 1,
            ),
            28 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2022-01-04 18:55:35',
                'description' => NULL,
                'id' => 37,
                'page_id' => 3,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 9,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-04 18:55:35',
                'vendor_template_id' => 1,
            ),
            29 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2022-01-06 14:16:17',
                'description' => NULL,
                'id' => 38,
                'page_id' => 5,
                'ref_comp_id' => NULL,
                'ref_post' => '1',
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-06 14:16:17',
                'vendor_template_id' => 1,
            ),
            30 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-29 16:51:12',
                'description' => NULL,
                'id' => 55,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-29 16:51:12',
                'vendor_template_id' => 1,
            ),
            31 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-29 16:51:26',
                'description' => NULL,
                'id' => 56,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-23 19:16:29',
                'vendor_template_id' => 1,
            ),
            32 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-29 16:51:38',
                'description' => NULL,
                'id' => 57,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 8,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-19 14:04:35',
                'vendor_template_id' => 1,
            ),
            33 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-29 16:51:53',
                'description' => NULL,
                'id' => 58,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 9,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-01-19 14:04:35',
                'vendor_template_id' => 1,
            ),
            34 => 
            array (
                'bg_color' => '#fbffe0',
                'component_id' => NULL,
                'component_name' => 'features',
                'created_at' => '2021-12-29 22:18:52',
                'description' => NULL,
                'id' => 60,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Features',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-23 19:17:16',
                'vendor_template_id' => 1,
            ),
            35 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'app_screen',
                'created_at' => '2021-12-29 22:25:43',
                'description' => NULL,
                'id' => 62,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 6,
                'title' => 'App Screen',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-23 19:21:08',
                'vendor_template_id' => 1,
            ),
            36 => 
            array (
                'bg_color' => '#fbffe0',
                'component_id' => NULL,
                'component_name' => 'contact_graphic',
                'created_at' => '2021-12-29 22:36:17',
                'description' => '<p>FoodTruck</p>',
                'id' => 63,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 7,
                'title' => 'Contact Graphic',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-23 19:25:11',
                'vendor_template_id' => 1,
            ),
            37 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'work_free',
                'created_at' => '2021-12-29 22:38:14',
                'description' => NULL,
                'id' => 64,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Work Free',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-23 19:19:59',
                'vendor_template_id' => 1,
            ),
            38 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'banner_app',
                'created_at' => '2022-01-19 13:59:55',
                'description' => NULL,
                'id' => 65,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 2,
                'title' => 'Banner App',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-23 19:14:54',
                'vendor_template_id' => 1,
            ),
            39 => 
            array (
                'bg_color' => '#fbffe0',
                'component_id' => NULL,
                'component_name' => 'process',
                'created_at' => '2022-01-20 10:21:32',
                'description' => NULL,
                'id' => 67,
                'page_id' => 11,
                'ref_comp_id' => NULL,
                'ref_post' => '10',
                'seq_no' => 5,
                'title' => 'Process',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-23 19:20:40',
                'vendor_template_id' => 1,
            ),
            40 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-29 16:51:12',
                'description' => NULL,
                'id' => 68,
                'page_id' => 20,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-29 16:51:12',
                'vendor_template_id' => 1,
            ),
            41 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-29 16:51:26',
                'description' => NULL,
                'id' => 69,
                'page_id' => 20,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 19:10:10',
                'vendor_template_id' => 1,
            ),
            42 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-29 16:51:38',
                'description' => NULL,
                'id' => 70,
                'page_id' => 20,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 13:44:52',
                'vendor_template_id' => 1,
            ),
            43 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-29 16:51:53',
                'description' => NULL,
                'id' => 71,
                'page_id' => 20,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 13:44:52',
                'vendor_template_id' => 1,
            ),
            44 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'contact_graphic_process',
                'created_at' => '2022-02-01 13:44:47',
                'description' => NULL,
                'id' => 78,
                'page_id' => 20,
                'ref_comp_id' => '78',
                'ref_post' => '20',
                'seq_no' => 2,
                'title' => 'Contact Graphic Process',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-03 19:10:39',
                'vendor_template_id' => 1,
            ),
            45 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-30 00:51:12',
                'description' => NULL,
                'id' => 79,
                'page_id' => 21,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-30 00:51:12',
                'vendor_template_id' => 1,
            ),
            46 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-30 00:51:26',
                'description' => NULL,
                'id' => 80,
                'page_id' => 21,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-04 03:10:10',
                'vendor_template_id' => 1,
            ),
            47 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-30 00:51:38',
                'description' => NULL,
                'id' => 81,
                'page_id' => 21,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 21:44:52',
                'vendor_template_id' => 1,
            ),
            48 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-30 00:51:53',
                'description' => NULL,
                'id' => 82,
                'page_id' => 21,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 21:44:52',
                'vendor_template_id' => 1,
            ),
            49 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'contact_graphic_process',
                'created_at' => '2022-02-01 21:44:47',
                'description' => NULL,
                'id' => 83,
                'page_id' => 21,
                'ref_comp_id' => '83',
                'ref_post' => '21',
                'seq_no' => 2,
                'title' => 'Contact Graphic Process',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-05 19:22:23',
                'vendor_template_id' => 1,
            ),
            50 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-30 00:51:12',
                'description' => NULL,
                'id' => 84,
                'page_id' => 22,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-30 00:51:12',
                'vendor_template_id' => 1,
            ),
            51 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-30 00:51:26',
                'description' => NULL,
                'id' => 85,
                'page_id' => 22,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-04 03:10:10',
                'vendor_template_id' => 1,
            ),
            52 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-30 00:51:38',
                'description' => NULL,
                'id' => 86,
                'page_id' => 22,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 21:44:52',
                'vendor_template_id' => 1,
            ),
            53 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-30 00:51:53',
                'description' => NULL,
                'id' => 87,
                'page_id' => 22,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 21:44:52',
                'vendor_template_id' => 1,
            ),
            54 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'contact_graphic_process',
                'created_at' => '2022-02-01 21:44:47',
                'description' => NULL,
                'id' => 88,
                'page_id' => 22,
                'ref_comp_id' => '88',
                'ref_post' => '22',
                'seq_no' => 2,
                'title' => 'Contact Graphic Process',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-06 19:22:13',
                'vendor_template_id' => 1,
            ),
            55 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-30 00:51:12',
                'description' => NULL,
                'id' => 99,
                'page_id' => 23,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-30 00:51:12',
                'vendor_template_id' => 1,
            ),
            56 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-30 00:51:26',
                'description' => NULL,
                'id' => 100,
                'page_id' => 23,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-04 03:10:10',
                'vendor_template_id' => 1,
            ),
            57 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-30 00:51:38',
                'description' => NULL,
                'id' => 101,
                'page_id' => 23,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 21:44:52',
                'vendor_template_id' => 1,
            ),
            58 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-30 00:51:53',
                'description' => NULL,
                'id' => 102,
                'page_id' => 23,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 21:44:52',
                'vendor_template_id' => 1,
            ),
            59 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'contact_graphic_process',
                'created_at' => '2022-02-01 21:44:47',
                'description' => NULL,
                'id' => 103,
                'page_id' => 23,
                'ref_comp_id' => '103',
                'ref_post' => '23',
                'seq_no' => 2,
                'title' => 'Contact Graphic Process',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-06 19:39:48',
                'vendor_template_id' => 1,
            ),
            60 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-30 00:51:12',
                'description' => NULL,
                'id' => 104,
                'page_id' => 24,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-30 00:51:12',
                'vendor_template_id' => 1,
            ),
            61 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-30 00:51:26',
                'description' => NULL,
                'id' => 105,
                'page_id' => 24,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-04 03:10:10',
                'vendor_template_id' => 1,
            ),
            62 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-30 00:51:38',
                'description' => NULL,
                'id' => 106,
                'page_id' => 24,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 21:44:52',
                'vendor_template_id' => 1,
            ),
            63 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-30 00:51:53',
                'description' => NULL,
                'id' => 107,
                'page_id' => 24,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-01 21:44:52',
                'vendor_template_id' => 1,
            ),
            64 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'contact_graphic_process',
                'created_at' => '2022-02-01 21:44:47',
                'description' => NULL,
                'id' => 108,
                'page_id' => 24,
                'ref_comp_id' => '108',
                'ref_post' => '24',
                'seq_no' => 2,
                'title' => 'Contact Graphic Process',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-06 19:48:13',
                'vendor_template_id' => 1,
            ),
            65 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-30 08:51:12',
                'description' => NULL,
                'id' => 109,
                'page_id' => 25,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-30 08:51:12',
                'vendor_template_id' => 1,
            ),
            66 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-30 08:51:26',
                'description' => NULL,
                'id' => 110,
                'page_id' => 25,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-04 11:10:10',
                'vendor_template_id' => 1,
            ),
            67 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-30 08:51:38',
                'description' => NULL,
                'id' => 111,
                'page_id' => 25,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 05:44:52',
                'vendor_template_id' => 1,
            ),
            68 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-30 08:51:53',
                'description' => NULL,
                'id' => 112,
                'page_id' => 25,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 05:44:52',
                'vendor_template_id' => 1,
            ),
            69 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'contact_graphic_process',
                'created_at' => '2022-02-02 05:44:47',
                'description' => NULL,
                'id' => 113,
                'page_id' => 25,
                'ref_comp_id' => '113',
                'ref_post' => '25',
                'seq_no' => 2,
                'title' => 'Contact Graphic Process',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-16 12:27:15',
                'vendor_template_id' => 1,
            ),
            70 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-30 16:51:12',
                'description' => NULL,
                'id' => 114,
                'page_id' => 26,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-30 16:51:12',
                'vendor_template_id' => 1,
            ),
            71 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-30 16:51:26',
                'description' => NULL,
                'id' => 115,
                'page_id' => 26,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-04 19:10:10',
                'vendor_template_id' => 1,
            ),
            72 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-30 16:51:38',
                'description' => NULL,
                'id' => 116,
                'page_id' => 26,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 13:44:52',
                'vendor_template_id' => 1,
            ),
            73 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-30 16:51:53',
                'description' => NULL,
                'id' => 117,
                'page_id' => 26,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 13:44:52',
                'vendor_template_id' => 1,
            ),
            74 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'contact_graphic_process',
                'created_at' => '2022-02-02 13:44:47',
                'description' => NULL,
                'id' => 118,
                'page_id' => 26,
                'ref_comp_id' => '118',
                'ref_post' => '26',
                'seq_no' => 2,
                'title' => 'Contact Graphic Process',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-16 12:32:31',
                'vendor_template_id' => 1,
            ),
            75 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-31 00:51:12',
                'description' => NULL,
                'id' => 119,
                'page_id' => 27,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-31 00:51:12',
                'vendor_template_id' => 1,
            ),
            76 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-31 00:51:26',
                'description' => NULL,
                'id' => 120,
                'page_id' => 27,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-05 03:10:10',
                'vendor_template_id' => 1,
            ),
            77 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-31 00:51:38',
                'description' => NULL,
                'id' => 121,
                'page_id' => 27,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 21:44:52',
                'vendor_template_id' => 1,
            ),
            78 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-31 00:51:53',
                'description' => NULL,
                'id' => 122,
                'page_id' => 27,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 21:44:52',
                'vendor_template_id' => 1,
            ),
            79 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'contact_graphic_process',
                'created_at' => '2022-02-02 21:44:47',
                'description' => NULL,
                'id' => 123,
                'page_id' => 27,
                'ref_comp_id' => '123',
                'ref_post' => '27',
                'seq_no' => 2,
                'title' => 'Contact Graphic Process',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-16 12:35:52',
                'vendor_template_id' => 1,
            ),
            80 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-31 00:51:12',
                'description' => NULL,
                'id' => 124,
                'page_id' => 28,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-16 14:04:49',
                'vendor_template_id' => 1,
            ),
            81 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-31 00:51:26',
                'description' => NULL,
                'id' => 125,
                'page_id' => 28,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-16 14:04:49',
                'vendor_template_id' => 1,
            ),
            82 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-31 00:51:38',
                'description' => NULL,
                'id' => 126,
                'page_id' => 28,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 5,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-16 14:04:41',
                'vendor_template_id' => 1,
            ),
            83 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-31 00:51:53',
                'description' => NULL,
                'id' => 127,
                'page_id' => 28,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 6,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-16 14:04:41',
                'vendor_template_id' => 1,
            ),
            84 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'about_us_banner',
                'created_at' => '2022-02-16 14:03:49',
                'description' => NULL,
                'id' => 129,
                'page_id' => 28,
                'ref_comp_id' => '129',
                'ref_post' => '28',
                'seq_no' => 2,
                'title' => 'About Us Banner',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-17 14:35:39',
                'vendor_template_id' => 1,
            ),
            85 => 
            array (
                'bg_color' => '#fbffe0',
                'component_id' => NULL,
                'component_name' => 'about_us_company',
                'created_at' => '2022-02-16 14:04:19',
                'description' => NULL,
                'id' => 130,
                'page_id' => 28,
                'ref_comp_id' => '130',
                'ref_post' => '28',
                'seq_no' => 3,
                'title' => 'About Us Company',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-17 14:36:20',
                'vendor_template_id' => 1,
            ),
            86 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'about_us_award',
                'created_at' => '2022-02-16 14:04:33',
                'description' => NULL,
                'id' => 131,
                'page_id' => 28,
                'ref_comp_id' => '131',
                'ref_post' => '28',
                'seq_no' => 4,
                'title' => 'About Us Award',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-17 19:15:16',
                'vendor_template_id' => 1,
            ),
            87 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-30 08:51:12',
                'description' => NULL,
                'id' => 137,
                'page_id' => 29,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-30 08:51:12',
                'vendor_template_id' => 1,
            ),
            88 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-30 08:51:26',
                'description' => NULL,
                'id' => 138,
                'page_id' => 29,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-04 11:10:10',
                'vendor_template_id' => 1,
            ),
            89 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-30 08:51:38',
                'description' => NULL,
                'id' => 139,
                'page_id' => 29,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 05:44:52',
                'vendor_template_id' => 1,
            ),
            90 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-30 08:51:53',
                'description' => NULL,
                'id' => 140,
                'page_id' => 29,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 05:44:52',
                'vendor_template_id' => 1,
            ),
            91 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'quote',
                'created_at' => '2022-02-18 07:58:26',
                'description' => NULL,
                'id' => 142,
                'page_id' => 29,
                'ref_comp_id' => '142',
                'ref_post' => '29',
                'seq_no' => 2,
                'title' => 'Quote',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-18 07:59:04',
                'vendor_template_id' => 1,
            ),
            92 => 
            array (
                'bg_color' => '#bc3838',
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-27 04:04:25',
                'description' => NULL,
                'id' => 143,
                'page_id' => 30,
                'ref_comp_id' => NULL,
                'ref_post' => 'header',
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => '#f45757',
                'type' => 'file',
                'updated_at' => '2022-01-11 20:24:09',
                'vendor_template_id' => 1,
            ),
            93 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-27 04:04:40',
                'description' => NULL,
                'id' => 144,
                'page_id' => 30,
                'ref_comp_id' => '2',
                'ref_post' => '19',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#7f9707',
                'type' => 'file',
                'updated_at' => '2022-02-03 22:51:29',
                'vendor_template_id' => 1,
            ),
            94 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-27 04:05:12',
                'description' => NULL,
                'id' => 146,
                'page_id' => 30,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-18 09:13:37',
                'vendor_template_id' => 1,
            ),
            95 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-27 04:05:29',
                'description' => '<p>test</p>',
                'id' => 147,
                'page_id' => 30,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-18 09:13:37',
                'vendor_template_id' => 1,
            ),
            96 => 
            array (
                'bg_color' => '#ffd540',
                'component_id' => NULL,
                'component_name' => 'portfolio',
                'created_at' => '2022-02-18 12:17:47',
                'description' => NULL,
                'id' => 151,
                'page_id' => 30,
                'ref_comp_id' => '9',
                'ref_post' => '19',
                'seq_no' => 2,
                'title' => 'Our Recent Work',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-18 19:44:10',
                'vendor_template_id' => 1,
            ),
            97 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-30 08:51:12',
                'description' => NULL,
                'id' => 152,
                'page_id' => 31,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-30 08:51:12',
                'vendor_template_id' => 1,
            ),
            98 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-30 08:51:26',
                'description' => NULL,
                'id' => 153,
                'page_id' => 31,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-04 11:10:10',
                'vendor_template_id' => 1,
            ),
            99 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-30 08:51:38',
                'description' => NULL,
                'id' => 154,
                'page_id' => 31,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 05:44:52',
                'vendor_template_id' => 1,
            ),
            100 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-30 08:51:53',
                'description' => NULL,
                'id' => 155,
                'page_id' => 31,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 05:44:52',
                'vendor_template_id' => 1,
            ),
            101 => 
            array (
                'bg_color' => '#000000',
                'component_id' => NULL,
                'component_name' => 'blog_banner_post',
                'created_at' => '2022-02-18 22:45:45',
                'description' => NULL,
                'id' => 157,
                'page_id' => 31,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 2,
                'title' => 'Blog Banner Post',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-18 22:48:00',
                'vendor_template_id' => 1,
            ),
            102 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'header',
                'created_at' => '2021-12-30 16:51:12',
                'description' => NULL,
                'id' => 158,
                'page_id' => 32,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 0,
                'title' => 'Header',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2021-12-30 16:51:12',
                'vendor_template_id' => 1,
            ),
            103 => 
            array (
                'bg_color' => '#ffffff',
                'component_id' => NULL,
                'component_name' => 'nav',
                'created_at' => '2021-12-30 16:51:26',
                'description' => NULL,
                'id' => 159,
                'page_id' => 32,
                'ref_comp_id' => '69',
                'ref_post' => '20',
                'seq_no' => 1,
                'title' => 'Nav',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-04 19:10:10',
                'vendor_template_id' => 1,
            ),
            104 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer',
                'created_at' => '2021-12-30 16:51:38',
                'description' => NULL,
                'id' => 160,
                'page_id' => 32,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 3,
                'title' => 'Footer',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 13:44:52',
                'vendor_template_id' => 1,
            ),
            105 => 
            array (
                'bg_color' => NULL,
                'component_id' => NULL,
                'component_name' => 'footer_small',
                'created_at' => '2021-12-30 16:51:53',
                'description' => NULL,
                'id' => 161,
                'page_id' => 32,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 4,
                'title' => 'Footer Small',
                'title_color' => NULL,
                'type' => 'file',
                'updated_at' => '2022-02-02 13:44:52',
                'vendor_template_id' => 1,
            ),
            106 => 
            array (
                'bg_color' => '#000000',
                'component_id' => NULL,
                'component_name' => 'blog_details',
                'created_at' => '2022-02-21 14:29:23',
                'description' => NULL,
                'id' => 164,
                'page_id' => 32,
                'ref_comp_id' => NULL,
                'ref_post' => NULL,
                'seq_no' => 2,
                'title' => 'Blog Details',
                'title_color' => '#000000',
                'type' => 'file',
                'updated_at' => '2022-02-21 14:29:28',
                'vendor_template_id' => 1,
            ),
        ));
        
        
    }
}